### ISSUE TITLE
 Bug with logging in.

### ISSUE THREAD

**Issue by Enano25** [tribotissues/tribotissues#18] opened 2017-04-28 20:58 UTC
Description of the bug (be specific): 
https://gyazo.com/58e3fc0488d19136638d596f5ff84d1a
If that message apears, tribot gets stuck and doesn't retry to log in. 
It should keep trying to log in as you can log in after 30-1 min afterwards.

How often the bug occurs: ALWAYS

Triggers of the bug (if known): 

Java version: https://gyazo.com/d3b94954bcb8648e0ffdcea141c2de34 Java Version: 1.8.0_101 32bit

Max Heap Size: 1024

TRiBot client version: TRiBot Version: TRiBot Release 9.304_5

Looking Glass (yes/no): no

Operating System: Operating System: Windows 7

Script Name: All scripts.

TRiBot Old-School or RS3: oldschool

Client Debug: n/a

Bot Debug: n/a

Screenshots (if any): https://gyazo.com/58e3fc0488d19136638d596f5ff84d1a

**Comment by Laniax** [comment] 2017-04-29 09:39
Duplicate of https://github.com/tribotissues/tribotissues/issues/16

**Closed** 2017-04-30 19:48 UTC
Labels: duplicate
